development:
  adapter: postgresql
  database: kentrikos_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: kentrikos_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: kentrikos_production
  pool: 5
  timeout: 5000
